- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

#gz topic published by Sensors plugin
- ros_topic_name: "velodyne_points"
  gz_topic_name: "velodyne_points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# DISABLED FOR NOW, ODOMETRY SEEMS TO NOT WORK FINE
# gz topic published by TrackedVehicle plugin
# - ros_topic_name: "odom"
#   gz_topic_name: "/model/jo/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS

# gz topic subscribed to by TrackedVehicle plugin
- ros_topic_name: "cmd_vel"
  gz_topic_name: "/model/jo/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ


# gz topic published by RGBDCamera plugin
- ros_topic_name: "front_camera/depth_image"
  gz_topic_name: "front_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS


# gz topic published by RGBDCamera plugin
- ros_topic_name: "back_camera/depth_image"
  gz_topic_name: "back_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS


- ros_topic_name: "front_camera/points"
  gz_topic_name: "front_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "back_camera/points"
  gz_topic_name: "back_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS


- ros_topic_name: "front_camera/camera_info"
  gz_topic_name: "front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "back_camera/camera_info"
  gz_topic_name: "back_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS


- ros_topic_name: "camera/camera_info"
  gz_topic_name: "camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Imu plugin
- ros_topic_name: "imu/data"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  